---
name: "ansible-runner"
author: "Jonathan Strickland"

dependencies:
  - base >= 4.7 && < 5
  - text
  - bytestring
  - typed-process
  - aeson
  - transformers
  - co-log-core
  - time
  - unordered-containers

library:
  source-dirs:
    - src/

default-extensions:
  - OverloadedStrings
  - NamedFieldPuns
  - ViewPatterns
  - PartialTypeSignatures
  - DataKinds
  - KindSignatures
